name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.45.3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 18

      - run: deno task build
      - run: npx jsr publish
